create table if not exists public.chart_metadata (
  id bigint generated by default as identity primary key,
  chart_key text not null unique,
  table_key text not null,
  table_title text not null,
  level smallint not null,
  song_title text not null,
  normalized_title text not null,
  chart_type text not null,
  category text not null default '미분류',
  source_sort_index integer not null default 999,
  classification_status text not null default 'uncategorized',
  bpm text not null default '',
  note_count integer not null default 0,
  type_info text not null default '',
  radar_notes numeric(6,2) not null default 0,
  radar_peak numeric(6,2) not null default 0,
  radar_scratch numeric(6,2) not null default 0,
  radar_soflan numeric(6,2) not null default 0,
  radar_charge numeric(6,2) not null default 0,
  radar_chord numeric(6,2) not null default 0,
  radar_top text not null default '',
  source text not null default 'manual',
  is_deleted boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chart_metadata_table_key_chk check (table_key in ('SP10H', 'SP11H', 'SP12H')),
  constraint chart_metadata_level_chk check (level between 10 and 12),
  constraint chart_metadata_chart_type_chk check (chart_type in ('H', 'A', 'L')),
  constraint chart_metadata_classification_status_chk check (classification_status in ('classified', 'provisional', 'uncategorized'))
);

create index if not exists chart_metadata_table_category_idx
  on public.chart_metadata (table_key, source_sort_index, category);

create index if not exists chart_metadata_title_idx
  on public.chart_metadata (normalized_title, chart_type);

create index if not exists chart_metadata_lookup_idx
  on public.chart_metadata (is_deleted, table_key, source_sort_index);

drop trigger if exists trg_chart_metadata_updated_at on public.chart_metadata;
create trigger trg_chart_metadata_updated_at
before update on public.chart_metadata
for each row execute procedure public.set_updated_at();
